# Discord token
token: "TOKEN"

# Channel ID 
channel: 123

# Bot will react to messages starting with following prefixes (no spaces allowed)
prefixes:
- "!shroom"
- "shroom"

# You can customize names of the commands
commands:
  help: "help"
  shitpost: "shitpost"
  eight_ball: "8ball"
  or: "or" # This command is meant to be in the middle of a message

# Elements of shitpost to generate, in order of appearance in the message
# You can add or remove strings or whole elements groups
shitpost:
-
  - "Gentelmen,"
  - "*EKHEM*!"
-
  - "someone once said something about"
  - "Sun Tzu wrote in Art of War, that"
-
  - "mushrooms being better than animals"
  - "I don't know what I'm talking about"
-
  - "and thats an undeniable fact."
  - "which even can be seen in the wall paintings in Lasco!"

# 8ball responses
responses:
- "Yes"
- "No"
- "Maybe"
- "Ask me later"
- "I don't know"

# Message sent to channel when the bot is started
enable_hello: true
hello: "Hello"

help: "**Commands**:\n
- `help`: Displays this message\n
- `shitpost`: Generates a random shitpost\n
- `eight_ball`: Answers given question\n
\n
**Features**:\n
- `or`: Chooses between two or more options"
