# Discord token
token: "TOKEN"

# Channel ID 
channel: 123

# Bot will react to messages starting with following prefixes (no spaces allowed)
prefixes:
- "!shroom"
- "shroom"

# You can customize names of the commands
commands:
  help: "help"
  or: "or" # This command is meant to be in the middle of a message

# Message sent to channel when the bot is started
enable_hello: true
hello: "Hello"

help: "**Commands**:\n
- `help`: Displays this message\n
\n
**Features**:\n
- `or`: Chooses between two or more options"