# Discord token
token: "TOKEN"

# Channel ID 
channel: 123

# Bot will react to messages starting with following prefixes (no spaces allowed)
prefixes:
- "!shroom"
- "shroom"

# You can customize names of the commands
commands:
  help: "help"
  shitpost: "shitpost"
  drunksay: "drunksay" # Shitpost, but in random order
  exchange: "exchange"
  eight_ball: "8ball"
  classify: "classify"
  remind: "remind"
  or: "or" # This command is meant to be in the middle of a message

# Elements of shitpost to generate, in order of appearance in the message
# You can add or remove strings or whole elements groups
shitpost:
-
  - "Gentelmen,"
  - "*EKHEM*!"
-
  - "someone once said something about"
  - "Sun Tzu wrote in Art of War, that"
-
  - "mushrooms being better than animals"
  - "I don't know what I'm talking about"
-
  - "and thats an undeniable fact."
  - "which even can be seen in the wall paintings in Lasco!"

# Exchange (default) settings
exchange:
  to: "to"
  input_amount: 1
  input_currency: "EUR"
  output_currency: "USD"

# 8ball responses
responses:
- "Yes"
- "No"
- "Maybe"
- "Ask me later"
- "I don't know"

# Categories into which the bot will classify messages
# You can define any set you like
classifiers:
- "cat"
- "dog"

# You can localize or alias time units
remind:
  omit: # words to ignore
    - "me"
    - "in"
  confirmation:
    - "OK"
  seconds:
    - "seconds"
    - "sec"
    - "s"
  minutes:
    - "minutes"
    - "min"
    - "m"
  hours:
    - "hours"
    - "h"

# Message sent to channel when the bot is started
enable_hello: true
hello: "Hello"

help: |
  **Commands**:
  - `help`: Displays this message
  - `shitpost`: Generates a random shitpost
  - `drunksay`: Generates a drunk shitpost
  - `eight_ball`: Answers given question
  - `exchange`: Convert between currencies and crypto
  - `classify`: Picks best way to describe your input
  - `remind`: Reminds you about something after a specified amount of time

  **Features**:
  - `or`: Chooses between two or more options

  **Code and documentation:**
  https://github.com/vllur/shroom
