# Discord token
token: "TOKEN"

# Channel ID 
channel: 123

# Bot will react to messages starting with following prefixes (no spaces allowed)
prefixes:
- "!shroom"
- "shroom"

# You can customize names of the commands
commands:
  help: "help"
  shitpost: "shitpost"
  drunksay: "drunksay" # Shitpost, but in random order
  exchange: "exchange"
  eight_ball: "8ball"
  classify: "classify"
  or: "or" # This command is meant to be in the middle of a message

# Elements of shitpost to generate, in order of appearance in the message
# You can add or remove strings or whole elements groups
shitpost:
-
  - "Gentelmen,"
  - "*EKHEM*!"
-
  - "someone once said something about"
  - "Sun Tzu wrote in Art of War, that"
-
  - "mushrooms being better than animals"
  - "I don't know what I'm talking about"
-
  - "and thats an undeniable fact."
  - "which even can be seen in the wall paintings in Lasco!"

# Exchange (default) settings
exchange:
  to: "to"
  input_amount: 1
  input_currency: "EUR"
  output_currency: "USD"

# 8ball responses
responses:
- "Yes"
- "No"
- "Maybe"
- "Ask me later"
- "I don't know"

# Categories into which the bot will classify messages
# You can define any set you like
classifiers:
- "cat"
- "dog"

# Message sent to channel when the bot is started
enable_hello: true
hello: "Hello"

help: "**Commands**:\n
- `help`: Displays this message\n
- `shitpost`: Generates a random shitpost\n
- `drunksay`: Generates a drunk shitpost\n
- `eight_ball`: Answers given question\n
- `exchange`: Convert between currencies and crypto\n
- `classify`: Picks best way to describe your input\n
\n
**Features**:\n
- `or`: Chooses between two or more options\n
\n
**Code and documentation:**\n
https://github.com/vllur/shroom"
